name: birthday_ui
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

flutter:
   fonts:
     - family: Jost
       fonts:
         - asset: assets/fonts/Jost-Italic-VariableFont_wght.ttf
         - asset: assets/fonts/Jost-VariableFont_wght.ttf
     - family: YesevaOne
       fonts:
         - asset: assets/fonts/YesevaOne-Regular.ttf
