// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9fGTCwpgD-nWsqhqOu4mw9yG6yxhav4',
    appId: '1:1091140346363:android:29b66391254448dba46b5e',
    messagingSenderId: '1091140346363',
    projectId: 'birthday-app-7f434',
    storageBucket: 'birthday-app-7f434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYRZV6S5fNW3q_nIQFsHnq9_B6AwgcoE4',
    appId: '1:1091140346363:ios:ed67588bf9a67faba46b5e',
    messagingSenderId: '1091140346363',
    projectId: 'birthday-app-7f434',
    storageBucket: 'birthday-app-7f434.appspot.com',
    iosClientId: '1091140346363-2dnr5r2j4i98ht9r6ejv25n86isnq2v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.birthdayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYRZV6S5fNW3q_nIQFsHnq9_B6AwgcoE4',
    appId: '1:1091140346363:ios:77761673864e6d07a46b5e',
    messagingSenderId: '1091140346363',
    projectId: 'birthday-app-7f434',
    storageBucket: 'birthday-app-7f434.appspot.com',
    iosClientId: '1091140346363-71voetje42uiatjlfucpv52ij2da7c90.apps.googleusercontent.com',
    iosBundleId: 'com.example.birthdayApp.RunnerTests',
  );
}
